examples/loopback:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3"]
    - if: IDF_TARGET == "linux" and IDF_VERSION >= "5.4.0"

examples/uart:
  enable:
    - if: IDF_TARGET in ["esp32s3", "esp32c6"]

examples/usb_cdc:
  enable:
    - if: IDF_TARGET in ["esp32s3", "esp32p4"]
