name: Upload component to the component registry
on:
  push:
    tags:
      - v*
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          namespace: "igrr"
          name: "rfc2217-server"
          version: ${{ github.ref_name }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
